###
GET http://localhost:8080/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia3dhbWUiLCJpYXQiOjE3NzQyNTc3ODl9.aN8z9zlImvSVMN_NSNeAvlRCllZ2iNAfmkfG2PpWsEE

###
POST http://localhost:8080/login
Content-Type: application/json

{
    "username" : "kwame"
}